environment:
  nodejs_version: '10'
install:
  - ps: Install-Product node $env:nodejs_version x64
  - yarn add -D nyc@11 @oclif/nyc-config@1
test_script:
  #  - .\bin\run --version
  - .\bin\run --help
  - .\node_modules\.bin\nyc --nycrc-path node_modules/@oclif/nyc-config/.nycrc yarn test
after_test:
  - .\node_modules\.bin\nyc --nycrc-path node_modules/@oclif/nyc-config/.nycrc report --reporter text-lcov > coverage.lcov
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh

build: off
